03_django/MTV/blog/urls.py
# mtv/urls.py (master URL)

from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    # blog/
    path('', views.index, name='index'),
    # blog/1 (detail)/
    path('<int:article_pk>/', views.detail, name='detail'),
    # blog/new/
    path('new/', views.new, name='new'),
    # blog/create/
    path('create/', views.create, name='create'),
    # blog/edit/
    path('<int:article_pk>/edit/', views.edit, name='edit'),
    # blog/update
    path('<int:article_pk>/update/', views.update, name='update'),
    # blog/delete/
    path('<int:article_pk>/delete/', views.delete, name='delete'),

]


'''
URL => 내 맘대로
1. Resource 를 표현
2. 명사형
3. 확실히 구분
4. (동사는 빼라)
'''

03_django/MTV/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # blog/
    path('', views.index, name='index'),
    # blog/1 (detail)/
    path('<int:posting_pk>/', views.detail, name='detail'),
    # blog/new/
    path('new/', views.new, name='new'),
    # blog/create/
    path('create/', views.create, name='create'),
    # blog/edit/
    path('<int:posting_pk>/edit/', views.edit, name='edit'),
    # blog/update
    path('<int:posting_pk>/update/', views.update, name='update'),
    # blog/delete/
    path('<int:posting_pk>/delete/', views.delete, name='delete'),

]

03_django/MTV/mtv/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('board/', include('board.urls')),
]

03_django/MTV/blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    # 생성 시, 자동으로 채워지도록
    created_at = models.DateTimeField(auto_now_add=True)
    # 생성/수정 시, 자동으로 채워지도록
    updated_at = models.DateTimeField(auto_now=True)

03_django/MTV/board/models.py
from django.db import models

# Create your models here.
class Posting(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # 생성 시, 자동으로 채워지도록
    created_at = models.DateTimeField(auto_now_add=True)
    # 생성/수정 시, 자동으로 채워지도록
    updated_at = models.DateTimeField(auto_now=True)

03_django/MTV/blog/views.py
from django.shortcuts import render, redirect
from .models import Article

# 글 목록 화면 (Read)
def index(request):
    # 글 목록 조회 
    # db article 관련된 레코드 전체를 조회
    articles = Article.objects.all()  # QuerySet(List)
    context = {
        'articles': articles,
    }
    return render(request, 'blog/index.html', context)

# 글 상세 화면 (Read)
def detail(request, article_pk):
    # db > articles > 특정 레코드 조회
    # pk = request.GET.get('no')
    print(type(article_pk))
    article = Article.objects.get(pk=article_pk)  # primary key 가 1인 것을 객체로 가져옴.
    context = { 'article': article, }
    return render(request, 'blog/detatil.html', context)


# 글 쓰기 화면 (Creat)
def new(request):
    return render(request, 'blog/new.html')

# 글 실제 저장
def create(request):
    article = Article()
    article.title = request.POST['title']
    article.content = request.POST['content']
    article.save()
    # hard redirect로 하는 방법
    # return redirect(f'/blog/{article.pk}/')  

    # detail 로 redirect 하자
    return redirect('blog:index', article.pk)

# 글 수정 화면 (Update)

def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = { 'article': article, }
    return render(request, 'blog/edit.html', context)

# 글 DB에  실제 수정
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.title = request.POST['title']
    article.content = request.POST['content']
    article.save()
    # 저장하고 detail로 redirect 하자!
    return redirect('blog:detail', article.pk)

# 글 삭제 ?? (Delete)
def delete(request, article_pk):
    if request.method == 'POST':
        # 특정 게시글을 지운다.
        # 1. 고른다.
        article = Article.objects.get(pk=article_pk)
        # 2. 지운다.
        article.delete()
    return redirect('blog:index')
    

03_django/MTV/board/views.py
from django.shortcuts import render, redirect
# 사용자의 요청에 대해 HTTP Response를 반환하기 위한 모듈
from django.http import HttpResponse
from .models import Posting

'''
# index() 함수, request를 파라미터로 받음(Django에 의해 자동으로 전달되는 HTTP 요청 객체)
def index(request):
    return HttpResponse("Main Board Page")  # 문자열을 사용자의 요청에 대한 응답으로 반환

from django.shortcuts import render, redirect
'''
# 글 목록 화면 (Read)
def index(request):
    # 글 목록 조회 
    # db article 관련된 레코드 전체를 조회
    postings = Posting.objects.all()  # QuerySet(List)
    context = {
        'postings': postings,
    }
    return render(request, 'board/index.html', context)

# 글 상세 화면 (Read)
def detail(request, posting_pk):
    # db > articles > 특정 레코드 조회
    # pk = request.GET.get('no')
    print(type(posting_pk))
    posting = Posting.objects.get(pk=posting_pk)  # primary key 가 1인 것을 객체로 가져옴.
    context = { 'posting': posting, }
    return render(request, 'board/detail.html', context)


# 글 쓰기 화면 (Creat)
def new(request):
    return render(request, 'posting/new.html')

# 글 실제 저장
def create(request):
    posting = Posting()
    posting.title = request.POST['title']
    posting.content = request.POST['content']
    posting.save()
    # hard redirect로 하는 방법
    # return redirect(f'/blog/{article.pk}/')  

    # detail 로 redirect 하자
    return redirect('board:index', posting.pk)

# 글 수정 화면 (Update)

def edit(request, posting_pk):
    posting = Posting.objects.get(pk=posting_pk)
    context = { 'postings': posting, }
    return render(request, 'board/edit.html', context)

# 글 DB에  실제 수정 
def update(request, posting_pk):
    posting = Posting.objects.get(pk=posting_pk)
    posting.title = request.POST['title']
    posting.content = request.POST['content']
    posting.save()
    # 저장하고 detail로 redirect 하자!
    return redirect('board:detail', posting_pk.pk)

# 글 삭제 ?? (Delete)
def delete(request, posting_pk):
    if request.method == 'POST':
        # 특정 게시글을 지운다.
        # 1. 고른다.
        posting = Posting.objects.get(pk=posting_pk)
        # 2. 지운다.
        posting.delete()
    return redirect('board:index')
    

03_django/MTV/blog/templates/blog/detail.html
{% include 'base.html' %}

{% block content %}
<h1>{{ article.title }}</h1>

<span>
    {{ article.created_at }}
    {{ article.updated_at}}
</span>

<p>
    {{ article.content }}
</p>

<div>
    {% comment %} 
    <a href="/blog/1/delete/"></a> 
    {% endcomment %}
    <a href="{% url 'blog:edit' article.pk  %}">
        <button>delete</button>
    </a>

    <form action="{% url 'blog:delete' article.pk  %}" method="POST">
        {% csrf_token %}
        <input type="submit" value='delete'>
    </form>
</div>

{% endlock content %}

03_django/MTV/blog/templates/blog/edit.html
{% include 'base.html' %}

{% block content %}

<h1>Edit Article</h1>

<form action="{% url 'blog:update' article.pk %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="title">title: </label>
        <input id="title" name="title" type="text" vlaue="{{ article.title }}">
    </div>

    <div>
        <label for="content">content: </label>
        <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}
        </textarea>
    </div>

    <div>
        <input type="submit" value="save">
    </div>
</form>



{% endblock content %}

03_django/MTV/blog/templates/blog/index.html
<!--blog/index.html-->

{%  include 'base.html' %}

{%  block content %}
<h1>Index</h1>

{% comment " 모든 게시글의 제목만 리스트로 확인" %}{% endcomment %}

<ul>
    {% comment %} 
        Python like => Django Template Language (DTL) 
        
        DTL
        - 괄호 없음
        - 쉽표 없음
        - 띄어쓰기로 구분        
    {% endcomment %}

    {%  for article in articles %}
        <li>
            <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
            {% comment %} 
            <a href="/blog/{{ article.pk }}/">{{ article.title }}</a> 
            {% endcomment %}
        </li>
    {% endfor %}     
</ul>



{%  endblock content %}

03_django/MTV/blog/templates/blog/new.html
{% include 'base.html' %}

{% block content %}

<h1>New Article</h1>

<form action="{% url 'blog:create' %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="title">title: </label>
        <input id="title" name="title" type="text">
    </div>

    <div>
        <label for="content">content: </label>
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>

    <div>
        <input type="submit" value="save">
    </div>
</form>



{% endblock content %}

03_django/MTV/board/templates/detail.html
{% include 'base.html' %}

{% block content %}
<h1>{{ posting.title }}</h1>

<span>
    {{ posting.created_at }}
    {{ posting.updated_at}}
</span>

<p>
    {{ posting.content }}
</p>

<div>
    {% comment %} 
    <a href="/blog/1/delete/"></a> 
    {% endcomment %}
    <a href="{% url 'board:edit' posting.pk  %}">
        <button>delete</button>
    </a>

    <form action="{% url 'board:delete' posting.pk  %}" method="POST">
        {% csrf_token %}
        <input type="submit" value='delete'>
    </form>
</div>

{% endlock content %}

03_django/MTV/board/templates/edit.html
{% include 'base.html' %}

{% block content %}

<h1>Edit Posting</h1>

<form action="{% url 'board:update' posting.pk %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="title">title: </label>
        <input id="title" name="title" type="text" vlaue="{{ posting.title }}">
    </div>

    <div>
        <label for="content">content: </label>
        <textarea name="content" id="content" cols="30" rows="10">{{ posting.content }}
        </textarea>
    </div>

    <div>
        <input type="submit" value="save">
    </div>
</form>



{% endblock content %}

03_django/MTV/board/templates/index.html
<!--blog/index.html-->

{%  include 'base.html' %}

{%  block content %}
<h1>Index</h1>

{% comment " 모든 게시글의 제목만 리스트로 확인" %}{% endcomment %}

<ul>
    {% comment %} 
        Python like => Django Template Language (DTL) 
        
        DTL
        - 괄호 없음
        - 쉽표 없음
        - 띄어쓰기로 구분        
    {% endcomment %}

    {%  for posting in postings %}
        <li>
            <a href="{% url 'board:detail' posting.pk %}">{{ posting.title }}</a>
            {% comment %} 
            <a href="/blog/{{ article.pk }}/">{{ article.title }}</a> 
            {% endcomment %}
        </li>
    {% endfor %}     
</ul>



{%  endblock content %}

03_django/MTV/board/templates/new.html
{% include 'base.html' %}

{% block content %}

<h1>New Posting</h1>

<form action="{% url 'board:create' %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="title">title: </label>
        <input id="title" name="title" type="text">
    </div>

    <div>
        <label for="content">content: </label>
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>

    <div>
        <input type="submit" value="save">
    </div>
</form>



{% endblock content %}

03_django/MTV/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'blog:index' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'blog:new' %}">New</a>
            </li>
        </ul>
    </nav>

    <nav>
        <ul>
            <li>
                <a href="{% url 'board:index' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'board:new' %}">New</a>
            </li>
        </ul>
    </nav>

    {% block content %}{% endblock content %}

</html>